using Simple.DatabaseWrapper.Attributes;

namespace ProcessaDados.App.Models.Db;

struct Item
{
    [PrimaryKey, AutoIncrement]
    public int Id { get; set; }
    public int ItemId { get; set; }
    public string Name { get; set; }
    public bool Purchased { get; set; }
    public ItemRarity Rarity { get; set; }
    public Hero Hero { get; set; }
}

public enum ItemRarity
{
    Common = 1,
    Uncommon = 2,
    Rare = 3,
    Mythical = 4,
    Legendary = 5,
    Ancient = 6,
    Immortal = 7,
    Arcana = 8
}

public enum Hero
{
    Antimage = 1,
    Axe = 2,
    Bane = 3,
    Bloodseeker = 4,
    CrystalMaiden = 5,
    DrowRanger = 6,
    Earthshaker = 7,
    Juggernaut = 8,
    Mirana = 9,
    Morphling = 10,
    Nevermore = 11,
    PhantomLancer = 12,
    Puck = 13,
    Pudge = 14,
    Razor = 15,
    SandKing = 16,
    StormSpirit = 17,
    Sven = 18,
    Tiny = 19,
    Vengefulspirit = 20,
    Windrunner = 21,
    Zuus = 22,
    Kunkka = 23,
    Lina = 25,
    Lion = 26,
    ShadowShaman = 27,
    Slardar = 28,
    Tidehunter = 29,
    WitchDoctor = 30,
    Lich = 31,
    Riki = 32,
    Enigma = 33,
    Tinker = 34,
    Sniper = 35,
    Necrolyte = 36,
    Warlock = 37,
    Beastmaster = 38,
    Queenofpain = 39,
    Venomancer = 40,
    FacelessVoid = 41,
    SkeletonKing = 42,
    DeathProphet = 43,
    PhantomAssassin = 44,
    Pugna = 45,
    TemplarAssassin = 46,
    Viper = 47,
    Luna = 48,
    DragonKnight = 49,
    Dazzle = 50,
    Rattletrap = 51,
    Leshrac = 52,
    Furion = 53,
    LifeStealer = 54,
    DarkSeer = 55,
    Clinkz = 56,
    Omniknight = 57,
    Enchantress = 58,
    Huskar = 59,
    NightStalker = 60,
    Broodmother = 61,
    BountyHunter = 62,
    Weaver = 63,
    Jakiro = 64,
    Batrider = 65,
    Chen = 66,
    Spectre = 67,
    AncientApparition = 68,
    DoomBringer = 69,
    Ursa = 70,
    SpiritBreaker = 71,
    Gyrocopter = 72,
    Alchemist = 73,
    Invoker = 74,
    Silencer = 75,
    ObsidianDestroyer = 76,
    Lycan = 77,
    Brewmaster = 78,
    ShadowDemon = 79,
    LoneDruid = 80,
    ChaosKnight = 81,
    Meepo = 82,
    Treant = 83,
    OgreMagi = 84,
    Undying = 85,
    Rubick = 86,
    Disruptor = 87,
    NyxAssassin = 88,
    NagaSiren = 89,
    KeeperOfTheLight = 90,
    Wisp = 91,
    Visage = 92,
    Slark = 93,
    Medusa = 94,
    TrollWarlord = 95,
    Centaur = 96,
    Magnataur = 97,
    Shredder = 98,
    Bristleback = 99,
    Tusk = 100,
    SkywrathMage = 101,
    Abaddon = 102,
    ElderTitan = 103,
    LegionCommander = 104,
    Techies = 105,
    EmberSpirit = 106,
    EarthSpirit = 107,
    AbyssalUnderlord = 108,
    Terrorblade = 109,
    Phoenix = 110,
    Oracle = 111,
    WinterWyvern = 112,
    ArcWarden = 113,
    MonkeyKing = 114,
    DarkWillow = 119,
    Pangolier = 120,
    Grimstroke = 121,
    Hoodwink = 123,
    VoidSpirit = 126,
    Snapfire = 128,
    Mars = 129,
    Ringmaster = 131,
    Dawnbreaker = 135,
    Marci = 136,
    PrimalBeast = 137,
    Muerta = 138,
    Kez = 145,
    Largo = 155
}